import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import localFont from "next/font/local";
import { Playfair_Display } from "next/font/google";
import Script from "next/script";
// import { Script } from "next/script";

// Body Font - Glacial Indifference
const glacial = localFont({
  src: [
    {
      path: "./fonts/GlacialIndifference-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/GlacialIndifference-Bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-glacial",
  display: "swap",
});

// Heading Font - Dream Avenue
const dreamAvenue = localFont({
  src: [
    {
      path: "./fonts/DreamAvenueRegular.otf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-dream",
  display: "swap",
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-playfair",
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
// import type { Metadata } from "next";

export const metadata: Metadata = {
  verification: {
    google: "cBN4zjNi31ZDGU0lFcmicGO9UA33TFdYDXHKa8ZVen8",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${glacial.variable} ${dreamAvenue.variable} ${playfair.variable}`}
    >
      <head>
        {/* Google Analytics */}
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-V5QBB5L9KE"
          strategy="afterInteractive"
        />

        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-V5QBB5L9KE');
          `}
        </Script>
      </head>
      <body className={`${glacial.variable} ${dreamAvenue.variable}`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
