import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import localFont from "next/font/local";

// Body Font - Glacial Indifference
const glacial = localFont({
  src: [
    {
      path: "./fonts/GlacialIndifference-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/GlacialIndifference-Bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-glacial",
  display: "swap",
});

// Heading Font - Dream Avenue
const dreamAvenue = localFont({
  src: [
    {
      path: "./fonts/DreamAvenueRegular.otf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-dream",
  display: "swap",
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${glacial.variable} ${dreamAvenue.variable}`}>
      <body className={`${glacial.variable} ${dreamAvenue.variable}`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
